In [1]:
def func():
    return("12")
def func():
    return("13")
print(func())

13


In [2]:
global a

a=2

def func():
    a=1
    b=2
    return (a+b)

print(func())

3


In [3]:
nums = [1,2,3,4,5]
func = lambda x: (x*2)
output = list(map(func, nums))
print(output)

[2, 4, 6, 8, 10]


In [1]:
x = "abcdef"
while i in x:
        print(i, end=" ")

NameError: name 'i' is not defined

In [2]:
def cube(x):
   return x * x * x      
x = cube(3)    
print (x)

27


In [3]:
print(((True) or (False) and (False) or (False)))

True


In [4]:
    x1=int('16')
    x2=8 + 8
    x3= (4**2)

    print(x1 is x2 is x3)

True


In [5]:
Word='warrior knights'
A=Word[9:14]
B=Word[-13:-16:-1]
B+A

'rawnight'

In [6]:
def to_upper(k):
   return k.upper()
x = ['ab', 'cd']
print(list(map(to_upper, x)))

['AB', 'CD']


In [7]:
my_string = "hello world"
k = [(i.upper(), len(i)) for i in my_string]
print(k)

[('H', 1), ('E', 1), ('L', 1), ('L', 1), ('O', 1), (' ', 1), ('W', 1), ('O', 1), ('R', 1), ('L', 1), ('D', 1)]


In [10]:
import numpy as np 
array=np.array([1,2,3,4,5,6,7,8,9,10])
dim=array.ndim
dim
reshaped=array.reshape(5,2)
reshaped

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [13]:
import numpy as np
# identity 4x4 matrix
array=np.eye(4)
array


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [1]:
import numpy as np

# Code starts here

# marks array
marks=np.array([20,30,40])

In [2]:
marks

array([20, 30, 40])

In [4]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [5]:
import numpy as np
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
import numpy as np
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
import numpy as np
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
a=np.array([[1,2],[3,4],[5,6]])

In [11]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
print(a[[0,1,2],[0,1,0]])
print('==========')

print(np.array([a[0,0],a[1,1],a[2,0]]))
print('==========')

print(a[[0,0],[1,1]])
print('==========')

print(np.array([a[0,1],a[0,1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [18]:
# Code starts here
import numpy as np
# initialize array
array=np.array([3,4.5,3+5j,0])
real=np.isreal(array)

# boolean filter
real_array=array[real]
imag=np.iscomplex(array)
imag_array=array[imag]


In [20]:
print(imag_array)

[3.+5.j]


In [21]:
print(real_array
     
     )

[3. +0.j 4.5+0.j 0. +0.j]


In [10]:
import numpy as np
# initialize array for prices
prices=np.array([[40,35,20],[21,48,70]])


# Code starts here

# flatten the array
prices=prices.flatten()
prices
# minimum price
buying_price=np.min(prices)
print(buying_price)
# index of buying price
index=list(prices).index(buying_price)
new_prices=prices[index:]
selling_price=np.max(new_prices)
print(selling_price)
profit=selling_price-buying_price
print(profit)

20
70
50


In [11]:
n=np.array([1, 2, 3]) + 4

In [12]:
n

array([5, 6, 7])

In [15]:
import numpy as np
np.random.seed(21)

# Code starts here

# create random 5x5 array
z=np.random.random((5,5))

# minimum and maximum values
zmax=np.max(z)
zmin=np.min(z)
print(zmax)
print(zmin)
z_range=zmax-zmin

# normalize
z_norm=(z-zmin)/z_range
print(z_norm)

0.9704851253491577
0.021616249915949792
[[0.02856942 0.28190767 0.73703555 0.         0.19423813]
 [0.03072817 0.29577917 0.67690496 0.3019365  0.59225784]
 [0.05053881 0.89136471 0.1176393  0.16494209 0.49987233]
 [0.88746023 0.77705951 1.         0.77743756 0.38217481]
 [0.40796162 0.72901978 0.26247412 0.87734633 0.93959001]]


In [17]:
# import packages
import numpy as np

# Code starts here

# co-efficients of x
coeff=np.array([1,-4,4]) 

# roots of equation
roots=np.roots(coeff)

# display roots
print(roots)

[2. 2.]


In [19]:
import numpy as np
# centigrade temperatures
centigrade_temps = np.array([0, 10, 25, 32, 80, 99.99])

# function for conversion
def convert(celsius):
    fahrehheit=celsius*9/5+32
    return fahrehheit


# display fahrehheit temperatures
fahrehheit_temps=convert(centigrade_temps)
print(fahrehheit_temps)

[ 32.     50.     77.     89.6   176.    211.982]


In [23]:

import numpy as np
# initialize matrix A and b
a=np.array([[2,1,2],[3,0,1],[1,1,-1]])
b=np.array([[-3],[5],[2]])
print(a)
print(b)

x=np.linalg.solve(a,b)
print(x)

# Check solution
check=np.allclose(np.dot(a,x),b)
print(check)

[[ 2  1  2]
 [ 3  0  1]
 [ 1  1 -1]]
[[-3]
 [ 5]
 [ 2]]
[[ 2.5]
 [-3. ]
 [-2.5]]
True


In [30]:
import numpy as np
# initialize array B and Identity matrix
B=np.array([[2,0,-1],[0,2,-1],[-1,0,1]])
I=np.identity(3)
print(I)
# calculate result
A=3*I-B
print(A)

# Code ends here

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 1.]
 [0. 1. 1.]
 [1. 0. 2.]]


In [1]:
# Importing header files
import numpy as np
import warnings

warnings.filterwarnings('ignore')

#New record
new_record=[[50,  9,  4,  1,  0,  0, 40,  0]]

#Reading file
data = np.genfromtxt(path, delimiter=",", skip_header=1)

#Code starts here
print(data)

NameError: name 'path' is not defined

In [2]:
import numpy as np
a = np.arange(9).reshape(3,3)
a


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
a[:,0]

array([0, 3, 6])

In [6]:
a[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [11]:
a[:1]

array([[0, 1, 2]])

In [9]:
np.size(a)

9

In [16]:
np.std(a)

2.581988897471611

In [1]:
race_0=a[a[:,2]==0]
race_1=a[a[:,2]==1]
print(race_1)

NameError: name 'a' is not defined

In [7]:
import pandas as pd
nums=[800678,800456]
names=['Richie','Mark']
series_1=pd.Series(nums,names)
print(series_1)
series_2=pd.Series(nums,index=names)
print(series_2)

Richie    800678
Mark      800456
dtype: int64
Richie    800678
Mark      800456
dtype: int64


In [24]:
import pandas as pd
a=pd.Series(data=[1,2,3,4],index=[0,1,2,3])
b=pd.Series(data=[1,2,3,4],index=[0,1,3,4])
c=a+b
print(c)
c.fillna(0,inplace=True)
b.fillna(0,inplace=True)
print(a)
print(c)

0    2.0
1    4.0
2    NaN
3    7.0
4    NaN
dtype: float64
0    1
1    2
2    3
3    4
dtype: int64
0    2.0
1    4.0
2    0.0
3    7.0
4    0.0
dtype: float64


In [39]:
import pandas as pd
pincodes=[800678,800456]
numbers=[2567890,2567657]
labels=['R','M']
first=pd.DataFrame(columns=['number','pincode'],index=labels)
print(first)


  number pincode
R    NaN     NaN
M    NaN     NaN
